name: z_network_discovery
description: Library that allows to ping IP subnet and discover network devices. Could be used to find other devices and services that are connected to the local network.
version: 0.3.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
